export const DATA_RECEIVED = 'DATA_RECEIVED';
export const FILTER_DATA = "FILTER_DATA";
export const RESET_FILTER = "RESET_FILTER";
export const SET_IS_ADD_NEW_UNIT = 'SET_IS_ADD_NEW_UNIT';
export const IS_DATA_UPDATED = 'IS_DATA_UPDATED';
