export const DATA_FILTERED = 'DATA_FILTERED';
export const DATA_RECEIVED = 'DATA_RECEIVED';
export const IS_DATA_FILTERED = 'IS_DATA_FILTERED';
export const IS_DATA_UPDATED = 'IS_DATA_UPDATED';
export const STATUS_RECEIVED = 'STATUS_RECEIVED';
export const ADD_NEW_TRUE = 'ADD_NEW_TRUE';
export const ADD_NEW_FALSE = 'ADD_NEW_FALSE';
export const RERENDER = 'RERENDER';
